plugins {
    id 'application'
    id 'java'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

repositories {
    mavenCentral()  // Required to download JUnit
}

dependencies {
    // The standard testing library for Java
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

application {
    mainClass = 'Main'
}

// Tells Gradle to use the modern JUnit 5 platform
test {
    useJUnitPlatform()
}
